# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MuleSoft API-Led Connectivity Workshop
email: nbalestra@salesforce.com
description: >- # this means to ignore newlines until "baseurl:"
  The API-Led connectivity workshop is a hands-on workshop that will help you understand how to design, build, secure, and manage APIs using MuleSoft Anypoint Platform.
domain: nbalestra.github.io
url: "https://nbalestra.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/alc-workshop" # the subpath of your site, e.g. /blog
#twitter_username: jekyllrb
github_username:  nbalestra

# Build settings
#theme: minima
theme: just-the-docs
#remote-theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

logo: /assets/images/mule-logo.png

#Theme configuration: https://just-the-docs.com/docs/configuration/

aux_links:
  "MuleSoft":
    - "https://www.mulesoft.com"

search_enabled: true

search: 
  heading_level: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

nav_enabled: true
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

nav_external_links:
  - title: MuleSoft
    url: https://www.mulesoft.com

nav_error_report: true

back_to_top: true
back_to_top_text: "Back to top"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
